# Header

menu:
  主页: /
  随笔: /categories/essay/
  项目: /categories/project/
  

# SubNav
subnav:
  github: "http://github.com/yvon-shong"
  weibo: "http://weibo.com/yiwenggogo"
  zhihu: "http://zhihu.com/people/yvon-shong"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  mail: "mailto:yvon@shong.win"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
url: http://asamaedu.com/blog/
root: /blog/

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: false
# 数学公式
mathjax: true
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '喝一杯 java'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: http://ww1.sinaimg.cn/large/6b2f6355ly1fyo438owfuj2083083jsc.jpg
# 微信二维码图片地址
weixin: http://ww1.sinaimg.cn/large/6b2f6355ly1fyo43wmet4j20gz0gvn07.jpg

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: http://ww1.sinaimg.cn/large/6b2f6355ly1fyo5ta11dqj226i26jb0m.jpg

#是否开启分享
share_jia: true

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
# duoshuo: shong


# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4acaa8'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false

smart_menu:
  innerArchive: '所有文章'
  aboutme: '关于我'
  friends: "友链"

aboutme: 自动驾驶从业者🚚 | TuSimple<br>微软大法传教士⛪️ | MSP <br>早稻田修士🌸 | Waseda University<br>vlogger🎥 | b站id yvonshong <br>还有少年热忱🙋🏻‍♂️

friends: 
  Yvon's Horizon | 知乎专栏: https://zhuanlan.zhihu.com/yvon-horizon
  微软大法好 | 知乎专栏: https://zhuanlan.zhihu.com/jiritsu-soko
  自律走行 | 知乎专栏: https://zhuanlan.zhihu.com/microsoft
  vlog 合辑 | bilibili: https://space.bilibili.com/6083595
  Waseda University | 早稻田大学: http://www.waseda.jp
  Southeast University | 东南大学: http://www.seu.edu.cn
  Chengdu No.7 Middle High School | 成都七中: http://www.cdqz.net
