# Header

menu:
  主页: /
  博文: /categories/essay/
  

# SubNav
subnav:
  weibo: "https://www.weibo.com/asamaedu"
  zhihu: "https://www.zhihu.com/org/qian-jian-liu-xue"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  mail: "mailto:contact@asamaedu.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
url: http://asamaedu.com/blog/
root: /blog/

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: false
# 数学公式
mathjax: true
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '喝一杯 java'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: http://ww1.sinaimg.cn/large/6b2f6355ly1fyo438owfuj2083083jsc.jpg
# 微信二维码图片地址
weixin: http://ww1.sinaimg.cn/large/6b2f6355ly1fyo43wmet4j20gz0gvn07.jpg

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: https://i.loli.net/2019/09/19/BzbYonf42XG7K9y.png

#是否开启分享
share_jia: true

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
# duoshuo: shong


# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#E186AF'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false

smart_menu:
  innerArchive: '所有文章'
  aboutme: '关于浅间'
  friends: "友链"

aboutme: 是2019年新兴的留学服务团队，团队皆为世界知名顶级高校硕士，分别来自日本东北帝国大学，日本早稻田大学，新加坡南洋理工大学，相识于成都七中，坚持聘用专业领域的专业顾问，为客户提供留学申请到就职咨询一系列服务和解决方案。

friends: 
  知乎: https://zhuanlan.zhihu.com/yvon-horizon
  微博: https://www.weibo.com/asamaedu
  成都七中: http://www.cdqz.net
